### ISSUE TITLE
A quick question on .Rot

### ISSUE THREAD

**Issue by hondaathma** [shichaoy/cuboid_detect#1]
Hi,
Thanks for the great work. I have a question about frame_calib_mat.Rot (% .Rot is camera rotation wrt. ground.). Is this the same as inverse perspective mapping? Do you know the value for Kitti?

**Comment by shichaoy** [comment]
@hondaathma  sorry for the late reply. I mainly monitor cube_slam package.  frame_calib.mat  Rot is the camera pose in the ground world frame. For kitti, it is quite simple because we can assume 
axis are aligned with ground, so Rot is [1 0 0;0 0 1 ;0 -1 0;]    camera x right, y down, z forward.   ground world frame is x right y forward, z upward
